# Face detection settings
face_detection:
  backend: "face_recognition"  # Options: "face_recognition", "mtcnn", "opencv"
  model: "hog"  # Options: "hog" (faster, fewer false positives) or "cnn" (more accurate) for face_recognition
  tolerance: 0.6
  min_face_size: 100  # Increased from 40 to reduce false positives on small objects
  confidence_threshold: 0.7  # Increased from 0.5 to filter low-confidence detections
  upsampling: 1  # For face_recognition backend
  # MTCNN specific settings
  mtcnn_thresholds: [0.6, 0.7, 0.7]
  mtcnn_scale_factor: 0.709
  # OpenCV specific settings
  opencv_scale_factor: 1.1
  opencv_min_neighbors: 3
  
# Video processing settings
video_processing:
  frame_interval: 30  # Process every N frames
  scene_change_threshold: 30.0
  max_faces_per_frame: 20
  batch_size: 32
  enable_gpu: true

# Output settings
output:
  chip_size: [224, 224]
  jpeg_quality: 85
  use_base64: true
  format: "json"  # Options: "json", "csv", "both"
  
# IPFS configuration
ipfs:
  api_endpoint: "http://localhost:5001"
  timeout: 30
  chunk_size: 262144  # 256KB chunks

# Blockchain configuration
blockchain:
  firefly_endpoint: "http://localhost:5000"
  namespace: "facial-vision"

# Face recognition settings (for existing functionality)
face_recognition:
  database_path: "data/face_db/faces.pkl"
  similarity_threshold: 0.2
  max_matches: 5
  encoding_jitter: 1
  min_faces_for_identity: 1

# Face clustering configuration
clustering:
  algorithm: "hdbscan"  # Options: "hdbscan", "dbscan", "agglomerative"
  min_cluster_size: 1
  min_samples: 1
  cluster_selection_epsilon: 0.2
  metric: "cosine"  # Options: "cosine", "euclidean" (cosine handled via normalization)
  cluster_registry_path: "data/cluster_registry.json"
  similarity_threshold: 0.9625
  eps: 0.3  # DBSCAN distance threshold (for cosine similarity)
  max_clusters: 1000
  incremental_update: true
  recompute_interval: 1000  # Recompute clusters after N new faces

# Maverix blockchain integration
maverix:
  base_url: "http://localhost:3000"
  provenance_endpoint: "/provenance/assets"
  retry_attempts: 3
  timeout: 30
  batch_upload: true
  max_batch_size: 50

# Path configuration
paths:
  base_dir: "."
  input: "data/input"
  output: "data/output"
  models: "data/models"
  temp: "data/temp"
  logs: "logs"

# Logging configuration
logging:
  level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
  format: "structured"  # Options: "simple", "structured", "json"
  file_rotation: "daily"
  max_files: 7
  console_output: true