blockchain:
  firefly_endpoint: http://localhost:5000
  namespace: facial-vision
clustering:
  algorithm: hdbscan
  cluster_registry_path: data/cluster_registry.json
  cluster_selection_epsilon: 0.2
  eps: 0.3
  incremental_update: true
  max_clusters: 1000
  metric: cosine
  min_cluster_size: 1
  min_samples: 1
  recompute_interval: 1000
  similarity_threshold: 0.91
face_detection:
  backend: face_recognition
  confidence_threshold: 0.7
  min_face_size: 100
  model: hog
  mtcnn_scale_factor: 0.709
  mtcnn_thresholds:
  - 0.6
  - 0.7
  - 0.7
  opencv_min_neighbors: 3
  opencv_scale_factor: 1.1
  tolerance: 0.6
  upsampling: 1
face_recognition:
  database_path: data/face_db/faces.pkl
  encoding_jitter: 1
  max_matches: 5
  min_faces_for_identity: 1
  similarity_threshold: 0.2
ipfs:
  api_endpoint: http://localhost:5001
  chunk_size: 262144
  timeout: 30
logging:
  console_output: true
  file_rotation: daily
  format: structured
  level: INFO
  max_files: 7
maverix:
  base_url: http://localhost:3000
  batch_upload: true
  max_batch_size: 50
  provenance_endpoint: /provenance/assets
  retry_attempts: 3
  timeout: 30
output:
  chip_size:
  - 224
  - 224
  format: json
  jpeg_quality: 85
  use_base64: true
paths:
  base_dir: .
  input: data/input
  logs: logs
  models: data/models
  output: data/output
  temp: data/temp
video_processing:
  batch_size: 32
  enable_gpu: true
  frame_interval: 30
  max_faces_per_frame: 20
  scene_change_threshold: 30.0
